#!/usr/bin/env python
"""Stage 3 runner: end-to-end accuracy on RULER-style tasks.

    python scripts/run_accuracy.py --dry-run
    python scripts/run_accuracy.py --out results/accuracy

--dry-run builds the pinned grid (configs/accuracy/stage3_grid.yaml),
generates examples, and reports what would run/skip -- no model load, no
GPU, no --dry-run/real-run divergence in the planning logic itself (same
plan()-is-the-single-source-of-truth discipline as scripts/run_sweep.py).

Backends have curated, asymmetric roles, not a uniform sweep grid:
  - one dense baseline (default: sdpa_math) covers the sparsity=0 reference
    point. Every exact-math kernel (SDPA/FA2/FA3/cuDNN/xFormers/Flex)
    computes identical attention and Stage 1 already verifies that against
    a float64 reference -- so only one needs to actually run here; running
    all of them would test kernel-selection noise, not attention-mechanism
    differences, and Stage 3 is about the latter.
  - block_sparse contributes its sparsity sweep (3 sparsity levels; the
    real kernel only supports block_size=128, not 64 -- see
    stage3_grid.yaml).
  - gla (linear attention) and sage (quantized, --include-sage) each
    contribute their own single operating point -- neither has a sparsity
    knob in this codebase's config model.

A row is a prefill plus greedy decode, not a single forward pass. Stage 3
scores generated TEXT against a RULER answer, so every cell runs the prompt
through the backend under test and then decodes to a stopping condition
(EOS, newline, or a per-task cap measured from real answer lengths -- see
attnbench/accuracy/stopping.py and docs/stage3_generation_decision.md).
Decode runs over a KV cache; without one the measured phase would be ~20x
larger and Stage 3 would not fit in a rented session.

Sparsity is applied during PREFILL ONLY. A block_sparse row's text is
generated by a dense kernel over the cache, and the row records both
backends -- see docs/limitations.md.

Before committing the full grid on a rented session, run
scripts/time_one_accuracy_example.py first -- the per-length cost estimates
in the Stage 3 planning doc are a FLOPs-based projection (assumed 15
TFLOPS effective throughput), not a measurement.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from attnbench.accuracy.config import load_grid                        # noqa: E402
from attnbench.accuracy.generation import (                            # noqa: E402
    ModelGeometry, StopTokens, generate_one)
from attnbench.accuracy.grid_configs import (                          # noqa: E402
    backend_instance, build_configs_by_backend, build_examples_by_task_length)
from attnbench.accuracy.sizing import approximate_token_count  # noqa: E402
from attnbench.accuracy.runner import build_cells, run_accuracy        # noqa: E402
from attnbench.accuracy import stopping                                # noqa: E402
from attnbench.config import AttnConfig                                # noqa: E402


def _dry_run_only(cfg, backend_name, example):
    raise AssertionError(
        "generate_fn was called during a --dry-run. Planning must never "
        "touch a model; if this fires, run_accuracy's dry_run branch has "
        "stopped short-circuiting and the dry run is no longer free.")


def build_generate_fn(grid, *, model_id: str, tokenizer, device: str,
                      dtype: str, score_cache_dir: str, verbose: bool = True):
    """The real execution path: load the model once, wrap it once, and
    return the per-cell closure `run_accuracy` calls.

    Built here rather than inside `run_accuracy` for the same reason
    `measure_fn` is injected into `run_sweep`: the driver's planning,
    resume and checkpoint logic stays testable on CPU with no model, and
    the part that genuinely needs a GPU is one function.

    The stop-token sets are derived ONCE from the vocabulary, not per call.
    A byte-level BPE vocabulary is ~150K entries and decoding it costs a few
    seconds; doing it per example would cost hours across the grid.
    """
    import torch
    from transformers import AutoModelForCausalLM

    from attnbench.accuracy.model import SwappableAttentionModel

    torch_dtype = getattr(torch, dtype)
    model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch_dtype)
    model = model.to(device).eval()

    geometry = ModelGeometry.from_config(model.config, dtype)
    # seq_len/batch on the template are placeholders: SwappedAttention.forward
    # derives both from the real tensors it receives, so this only carries
    # geometry and dtype.
    cfg_template = geometry.onto(
        AttnConfig(seq_len=max(grid.seq_lens), batch=1, n_heads_q=1,
                   n_heads_kv=1, head_dim=128, mask="causal"),
        seq_len=max(grid.seq_lens))
    wrapped = SwappableAttentionModel(model, cfg_template, model_id=model_id,
                                      finest_block_size=grid.finest_block_size)

    stop_tokens = StopTokens.from_tokenizer(
        tokenizer, getattr(model, "generation_config", None))
    if verbose:
        print(f"stop tokens   : {len(stop_tokens.eos)} eos, "
              f"{len(stop_tokens.newline)} newline, "
              f"{len(stop_tokens.whitespace)} whitespace-only (from the vocab)")
        print("                EOS is expected to fire ~never -- RULER prompts "
              "are completion-style;")
        print("                the newline stop is what actually terminates an "
              "answer. See stopping.py.")
    if not stop_tokens.newline:
        # Loud, not a warning buried in a log. Without a newline set every
        # example runs to its cap: the run still produces rows, the truncation
        # rate reads ~100% for every backend, and nothing downstream can tell
        # that from a real finding.
        raise SystemExit(
            f"{model_id}'s vocabulary yields no newline tokens, so the stopping "
            f"rule reduces to the per-task cap. Every example would exit on "
            f"truncation and the per-backend truncation rate -- a headline "
            f"Stage 3 output -- would carry no information. Fix the derivation "
            f"in accuracy/stopping.py before running.")

    backends_by_name: dict = {}

    def generate_fn(cfg, backend_name, example):
        backend = backends_by_name.get(backend_name)
        if backend is None:
            backend = backends_by_name[backend_name] = backend_instance(backend_name)
        return generate_one(wrapped, tokenizer, cfg=cfg, backend=backend,
                            example=example, geometry=geometry,
                            stop_tokens=stop_tokens,
                            score_cache_dir=score_cache_dir, device=device)

    generate_fn.unwrap = wrapped.unwrap
    return generate_fn


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--grid", default="configs/accuracy/stage3_grid.yaml")
    ap.add_argument("--out", default="results/accuracy")
    ap.add_argument("--include-sage", action="store_true",
                    help="Include the sage backend (conditional on H100 "
                         "quota per the Stage 3 plan; needs a real "
                         "quant_scheme confirmed and a matching gates.TOL "
                         "entry before this produces trustworthy rows).")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--dtype", default="bfloat16")
    ap.add_argument("--allow-mixed-commits", action="store_true",
                    help="resume into a checkpoint written at a different "
                         "commit. Stage 3 runs across several sessions and a "
                         "repository change between them makes the remainder "
                         "a different experiment -- see runner.check_code_"
                         "continuity for what you are asserting.")
    ap.add_argument("--allow-dirty", action="store_true",
                    help="run from, or resume into, a tree with uncommitted "
                         "changes. The commit stamped on those rows then "
                         "does not establish what code produced them.")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    grid = load_grid(args.grid)
    print(f"grid          : {args.grid}")
    print(f"model primary : {grid.model_primary}")
    print(f"model alt     : {grid.model_alternate}")
    print(f"tasks         : {', '.join(grid.tasks)}")
    print("seq_lens (n)  : " + ", ".join(
        f"{s}{'*' if grid.is_directional(s) else ''}={n}"
        for s, n in sorted(grid.seq_lens.items())))
    print("                (* = directional/underpowered point, see stage3_grid.yaml)")

    # Contexts are sized against a real tokenizer so a grid seq_len is an
    # exact token count (see attnbench/accuracy/sizing.py). A --dry-run only
    # exercises planning/cell-counting and must not require downloading a
    # tokenizer, so it uses the explicitly-named approximate counter -- and
    # says so, because a silent estimate is the failure this replaced.
    if args.dry_run:
        print("sizing        : APPROXIMATE (--dry-run; no tokenizer loaded) "
              "-- context lengths are structural only, not real token counts")
        count_tokens = approximate_token_count
    else:
        from transformers import AutoTokenizer
        tokenizer = AutoTokenizer.from_pretrained(grid.model_primary)

        def count_tokens(text: str) -> int:
            return len(tokenizer(text).input_ids)

        print(f"sizing        : exact, via {grid.model_primary} tokenizer")

    examples_by_task_length = build_examples_by_task_length(
        grid, seed=args.seed, count_tokens=count_tokens)
    examples_by_id = {
        (task, ex.example_id): ex
        for (task, _seq_len), exs in examples_by_task_length.items()
        for ex in exs
    }

    configs_by_backend = build_configs_by_backend(grid, include_sage=args.include_sage)
    print(f"backends      : {', '.join(configs_by_backend)}")
    print("caps (tokens) : " + ", ".join(
        f"{t}={stopping.token_cap(t)}" for t in grid.tasks))

    cells = build_cells(configs_by_backend=configs_by_backend,
                        examples_by_task_length=examples_by_task_length)

    if args.dry_run:
        generate_fn = _dry_run_only
        teardown = None
    else:
        generate_fn = build_generate_fn(
            grid, model_id=grid.model_primary, tokenizer=tokenizer,
            device=args.device, dtype=args.dtype,
            score_cache_dir=grid.score_cache_dir)
        teardown = generate_fn.unwrap

    try:
        report = run_accuracy(cells, out_dir=Path(args.out),
                              examples_by_id=examples_by_id,
                              generate_fn=generate_fn, dry_run=args.dry_run,
                              allow_mixed_commits=args.allow_mixed_commits,
                              allow_dirty=args.allow_dirty)
    finally:
        if teardown is not None:
            teardown()

    print(f"\ntotal cells   : {report.total}")
    print(f"would run     : {report.run}")
    print(f"skip (done)   : {report.skip_done}")
    if args.dry_run:
        print("\n[dry run -- nothing executed, nothing written]")
    else:
        print(f"\nwritten to {args.out}/accuracy.parquet")


if __name__ == "__main__":
    main()
