#!/usr/bin/env python
"""Stage 3 runner: end-to-end accuracy on RULER-style tasks.

    python scripts/run_accuracy.py --dry-run
    python scripts/run_accuracy.py --out results/accuracy

--dry-run builds the pinned grid (configs/accuracy/stage3_grid.yaml),
generates examples, and reports what would run/skip -- no model load, no
GPU, no --dry-run/real-run divergence in the planning logic itself (same
plan()-is-the-single-source-of-truth discipline as scripts/run_sweep.py).

Backends have curated, asymmetric roles, not a uniform sweep grid:
  - one dense baseline (default: sdpa_math) covers the sparsity=0 reference
    point. Every exact-math kernel (SDPA/FA2/FA3/cuDNN/xFormers/Flex)
    computes identical attention and Stage 1 already verifies that against
    a float64 reference -- so only one needs to actually run here; running
    all of them would test kernel-selection noise, not attention-mechanism
    differences, and Stage 3 is about the latter.
  - block_sparse contributes its sparsity sweep (3 sparsity levels; the
    real kernel only supports block_size=128, not 64 -- see
    stage3_grid.yaml).
  - gla (linear attention) and sage (quantized, --include-sage) each
    contribute their own single operating point -- neither has a sparsity
    knob in this codebase's config model.

A row is a prefill plus greedy decode, not a single forward pass. Stage 3
scores generated TEXT against a RULER answer, so every cell runs the prompt
through the backend under test and then decodes to a stopping condition
(EOS, newline, or a per-task cap measured from real answer lengths -- see
attnbench/accuracy/stopping.py and docs/stage3_generation_decision.md).
Decode runs over a KV cache; without one the measured phase would be ~20x
larger and Stage 3 would not fit in a rented session.

Sparsity is applied during PREFILL ONLY. A block_sparse row's text is
generated by a dense kernel over the cache, and the row records both
backends -- see docs/limitations.md.

Before committing the full grid on a rented session, run
scripts/time_one_accuracy_example.py first -- the per-length cost estimates
in the Stage 3 planning doc are a FLOPs-based projection (assumed 15
TFLOPS effective throughput), not a measurement.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from attnbench.accuracy.config import load_grid                        # noqa: E402
from attnbench.accuracy.generation import (                            # noqa: E402
    ModelGeometry, StopTokens, generate_one)
from attnbench.accuracy.grid_configs import (                          # noqa: E402
    backend_instance, build_configs_by_backend, build_examples_by_task_length)
from attnbench.accuracy.schema import GATED_BACKENDS                   # noqa: E402
from attnbench.accuracy.sizing import approximate_token_count  # noqa: E402
from attnbench.accuracy.runner import build_cells, run_accuracy        # noqa: E402
from attnbench.accuracy import stopping                                # noqa: E402
from attnbench import provenance                                       # noqa: E402
from attnbench.config import AttnConfig                                # noqa: E402


def _dry_run_only(cfg, backend_name, example):
    raise AssertionError(
        "generate_fn was called during a --dry-run. Planning must never "
        "touch a model; if this fires, run_accuracy's dry_run branch has "
        "stopped short-circuiting and the dry run is no longer free.")


def _guard_model_fits(model_id: str, device: str) -> None:
    """Refuse a --model that cannot fit, BEFORE the boot is spent on it.

    The failure this prevents is not an OOM -- it is an OOM discovered after
    the tokenizer has downloaded, the examples have been built and the clocks
    have been locked, on a rented instance. Same shape as the Stage 1 gate and
    the GCS write gate: check the precondition while failing is still free.

    Weights only, bf16, from the HF config -- activations are not modelled,
    which is why the headroom factor is deliberately generous.
    """
    import torch
    if not device.startswith("cuda") or not torch.cuda.is_available():
        return
    from transformers import AutoConfig
    cfg = AutoConfig.from_pretrained(model_id)
    n = getattr(cfg, "num_parameters", None)
    if n is None:
        h = cfg.hidden_size
        L = cfg.num_hidden_layers
        v = cfg.vocab_size
        inter = getattr(cfg, "intermediate_size", 4 * h)
        n = L * (4 * h * h + 3 * h * inter) + 2 * v * h   # attn + mlp + embeds
    weights_gb = n * 2 / 1e9                              # bf16
    total_gb = torch.cuda.get_device_properties(0).total_memory / 1e9
    if weights_gb * 2.5 > total_gb:
        raise SystemExit(
            f"REFUSING --model {model_id}: ~{weights_gb:.1f} GB of bf16 weights "
            f"needs >{weights_gb * 2.5:.1f} GB with activation headroom, but "
            f"{torch.cuda.get_device_name()} has {total_gb:.1f} GB. "
            f"Run it on a card that fits, or drop --model."
        )
    print(f"model guard   : {model_id} ~{weights_gb:.1f} GB weights on a "
          f"{total_gb:.1f} GB device -- ok")


def build_generate_fn(grid, *, model_id: str, tokenizer, device: str,
                      dtype: str, score_cache_dir: str, verbose: bool = True,
                      gla_gate_source: str | None = None,
                      score_source: str = "dense_softmax_fp32"):
    """The real execution path: load the model once, wrap it once, and
    return the per-cell closure `run_accuracy` calls.

    Built here rather than inside `run_accuracy` for the same reason
    `measure_fn` is injected into `run_sweep`: the driver's planning,
    resume and checkpoint logic stays testable on CPU with no model, and
    the part that genuinely needs a GPU is one function.

    The stop-token sets are derived ONCE from the vocabulary, not per call.
    A byte-level BPE vocabulary is ~150K entries and decoding it costs a few
    seconds; doing it per example would cost hours across the grid.
    """
    import torch
    from transformers import AutoModelForCausalLM

    from attnbench.accuracy.model import SwappableAttentionModel

    torch_dtype = getattr(torch, dtype)
    model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch_dtype)
    model = model.to(device).eval()

    geometry = ModelGeometry.from_config(model.config, dtype)
    # seq_len/batch on the template are placeholders: SwappedAttention.forward
    # derives both from the real tensors it receives, so this only carries
    # geometry and dtype.
    cfg_template = geometry.onto(
        AttnConfig(seq_len=max(grid.seq_lens), batch=1, n_heads_q=1,
                   n_heads_kv=1, head_dim=128, mask="causal"),
        seq_len=max(grid.seq_lens))
    wrapped = SwappableAttentionModel(model, cfg_template, model_id=model_id,
                                      finest_block_size=grid.finest_block_size,
                                      score_source=score_source)

    stop_tokens = StopTokens.from_tokenizer(
        tokenizer, getattr(model, "generation_config", None))
    if verbose:
        print(f"stop tokens   : {len(stop_tokens.eos)} eos, "
              f"{len(stop_tokens.newline)} newline, "
              f"{len(stop_tokens.whitespace)} whitespace-only (from the vocab)")
        print("                EOS is expected to fire ~never -- RULER prompts "
              "are completion-style;")
        print("                the newline stop is what actually terminates an "
              "answer. See stopping.py.")
    if not stop_tokens.newline:
        # Loud, not a warning buried in a log. Without a newline set every
        # example runs to its cap: the run still produces rows, the truncation
        # rate reads ~100% for every backend, and nothing downstream can tell
        # that from a real finding.
        raise SystemExit(
            f"{model_id}'s vocabulary yields no newline tokens, so the stopping "
            f"rule reduces to the per-task cap. Every example would exit on "
            f"truncation and the per-backend truncation rate -- a headline "
            f"Stage 3 output -- would carry no information. Fix the derivation "
            f"in accuracy/stopping.py before running.")

    backends_by_name: dict = {}

    def generate_fn(cfg, backend_name, example):
        backend = backends_by_name.get(backend_name)
        if backend is None:
            # Only the gated backends take the keyword; backend_instance
            # refuses it for the rest rather than ignoring it.
            kw = ({"gate_source": gla_gate_source}
                  if gla_gate_source and backend_name in GATED_BACKENDS else {})
            backend = backends_by_name[backend_name] = backend_instance(
                backend_name, **kw)
        return generate_one(wrapped, tokenizer, cfg=cfg, backend=backend,
                            example=example, geometry=geometry,
                            stop_tokens=stop_tokens,
                            score_cache_dir=score_cache_dir, device=device)

    generate_fn.unwrap = wrapped.unwrap
    return generate_fn


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--grid", default="configs/accuracy/stage3_grid.yaml")
    ap.add_argument("--out", default="results/accuracy")
    ap.add_argument("--include-sage", action="store_true",
                    help="Include the sage backend (conditional on H100 "
                         "quota per the Stage 3 plan; needs a real "
                         "quant_scheme confirmed and a matching gates.TOL "
                         "entry before this produces trustworthy rows).")
    ap.add_argument("--score-source", default="dense_softmax_fp32",
                    choices=["dense_softmax_fp32", "minference_meanpool"],
                    help="which importance scorer produces the ranking behind "
                         "every block_sparse mask in this run. "
                         "dense_softmax_fp32 is the oracle: a full dense "
                         "softmax pass, an upper bound on achievable accuracy "
                         "whose cost is excluded from every latency number. "
                         "minference_meanpool is the deployable estimator "
                         "(MInference 1.0, arXiv:2407.02490, Algorithm 3), "
                         "which pools Q and K before scoring and never forms "
                         "an S x S matrix. The value is stamped on every row "
                         "and hashed into the score-cache key.")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--dtype", default="bfloat16")
    ap.add_argument("--allow-mixed-commits", action="store_true",
                    help="resume into a checkpoint written at a different "
                         "commit. Stage 3 runs across several sessions and a "
                         "repository change between them makes the remainder "
                         "a different experiment -- see runner.check_code_"
                         "continuity for what you are asserting.")
    ap.add_argument("--allow-dirty", action="store_true",
                    help="run from, or resume into, a tree with uncommitted "
                         "changes. The commit stamped on those rows then "
                         "does not establish what code produced them.")
    ap.add_argument("--seq-lens", default=None,
                    help="comma-separated bands to run, e.g. 2048,4096. "
                         "Defaults to every band in the grid. Stage 3 runs in "
                         "band-aligned segments (docs/stage3_segmentation.md) "
                         "because a band boundary leaves no partially-scored "
                         "band to reconstruct -- so a segment is expressed "
                         "here rather than by editing the pinned grid, which "
                         "would change what every OTHER segment measured.")
    ap.add_argument("--model", default=None,
                    help="run against this model INSTEAD of the grid's "
                         "model_primary. The grid pins two ~1.5B models "
                         "because its header assumes a 24GB ceiling "
                         "(docs/hardware_constraints.md); a larger model is a "
                         "deliberate act on hardware that fits it, not a "
                         "default. Guarded: the run refuses unless the "
                         "device has room for the weights with headroom, "
                         "because discovering an OOM after the tokenizer and "
                         "the examples are built wastes the boot.")
    ap.add_argument("--tasks", default=None,
                    help="comma-separated subset of the pinned grid's tasks. "
                         "Like --seq-lens, a subset is expressed here rather "
                         "than by editing the grid, which would change what "
                         "every other segment measured.")
    ap.add_argument("--n-per-length", type=int, default=None,
                    help="cap examples per (task, band). Must not exceed the "
                         "grid's own n: examples are seeded per index, so a "
                         "smaller n is the PREFIX of the full set and stays "
                         "paired with banked rows. A larger one would not be "
                         "a subset of anything already measured.")
    ap.add_argument("--lock-clocks", action="store_true",
                    help="pin SM clocks before measuring, and stamp the "
                         "OUTCOME on every row. Not the intent -- "
                         "provenance.lock_clocks returns whether it actually "
                         "worked, which it did not do until 2026-09-06.")
    ap.add_argument("--gla-gate-source", default=None,
                    choices=("synthetic", "ungated"),
                    help="which forget gate the gla arm runs with. NO "
                         "DEFAULT: omitted leaves the backend on 'learned', "
                         "which refuses to run, because Qwen2.5 has no gate "
                         "projection to borrow and there is no correct value "
                         "(docs/gla_arm_decision.md). 'ungated' is the only "
                         "one that can produce a readable accuracy row, and "
                         "only if the pre-registered rule returned KEEP. "
                         "'learned' is deliberately not offered here -- it is "
                         "the thing this study does not have, not a choice. "
                         "Whatever is passed lands in the gate_source column "
                         "of every gla row.")
    ap.add_argument("--no-gla", action="store_true",
                    help="drop the gla arm entirely. This is what a DROP "
                         "verdict from docs/gla_arm_decision.md does; without "
                         "it the rule could reach a decision the pipeline had "
                         "no way to act on.")
    ap.add_argument("--only-backends", default=None,
                    help="comma-separated subset of the grid's backends to run "
                         "(e.g. sdpa_flash). Narrows the grid, never adds to it. "
                         "Exists so a dense canary can run and be checked "
                         "BEFORE any sparse row is measured: run the dense arm "
                         "alone, check it, then run again without this flag -- "
                         "resume skips the dense rows already written.")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    # The gla arm is decided by docs/gla_arm_decision.md, and this is where
    # either verdict becomes an action. First thing after parsing, before the
    # grid, the tokenizer or the model: the failure it prevents is a 4-hour
    # band dying on its last 900 cells and taking the chained bands after it,
    # and a guard that fires late has already let the cost happen. gla's
    # default gate refuses, so an unstated choice is not a quiet skip.
    if args.no_gla and args.gla_gate_source:
        raise SystemExit(
            "--no-gla and --gla-gate-source are contradictory: one drops the "
            "arm, the other configures it. Pass whichever the verdict in "
            "results/.../gla_arm_verdict.json calls for, not both.")
    if not args.no_gla and not args.gla_gate_source and not args.dry_run:
        raise SystemExit(
            "the gla arm is included but no --gla-gate-source was given.\n\n"
            "gla's default gate refuses to run (Qwen2.5 has no gate "
            "projection to borrow), so this would raise on the first gla "
            "cell -- after every dense and sparse row of the band had "
            "already been paid for.\n\n"
            "Run scripts/decide_gla_arm.py first, then pass either\n"
            "  --gla-gate-source ungated   (verdict KEEP)\n"
            "  --no-gla                    (verdict DROP)\n"
            "See docs/gla_arm_decision.md.")

    grid = load_grid(args.grid)

    # Band restriction. Applied to the LOADED grid, never to the file: the
    # grid is pinned data and every segment must agree about what the whole
    # experiment is, or the segments cannot be joined.
    #
    # Examples are generated per (task, seq_len) from the same seed, so a
    # band's examples are identical whether or not other bands run alongside
    # it -- asserted in tests/test_grid_configs.py rather than assumed, since
    # a segment that silently re-randomised its own band would produce rows
    # that resume-skip against nothing.
    if args.seq_lens:
        requested = [int(x) for x in args.seq_lens.split(",") if x.strip()]
        unknown = [s for s in requested if s not in grid.seq_lens]
        if unknown:
            raise SystemExit(
                f"--seq-lens {unknown} are not in the pinned grid "
                f"({sorted(grid.seq_lens)}). A band this study did not plan "
                f"is not a band it can report.")
        selected_seq_lens = {s: grid.seq_lens[s] for s in sorted(requested)}
    else:
        selected_seq_lens = dict(grid.seq_lens)

    # Same reasoning as --seq-lens: a task this study did not plan is not a
    # task it can report, and the subset must be expressed here rather than
    # in the pinned grid.
    if args.tasks:
        requested_tasks = tuple(t.strip() for t in args.tasks.split(",") if t.strip())
        unknown = [t for t in requested_tasks if t not in grid.tasks]
        if unknown:
            raise SystemExit(
                f"--tasks {unknown} are not in the pinned grid "
                f"({list(grid.tasks)}). A task this study did not plan is "
                f"not a task it can report.")
        selected_tasks = requested_tasks
    else:
        selected_tasks = tuple(grid.tasks)

    # A smaller n is the prefix of the grid's set -- examples are seeded per
    # (seed, task, budget, index) and the filler fit is solved from index 0,
    # so example k is identical whether n is 100 or 300 (asserted in
    # tests/test_ruler_integration.py). That is what keeps a reduced re-run
    # PAIRED with the banked rows. A LARGER n would add examples no banked
    # row has a partner for, so it is refused rather than silently allowed.
    if args.n_per_length is not None:
        if args.n_per_length < 1:
            raise SystemExit("--n-per-length must be at least 1")
        too_big = {s: n for s, n in selected_seq_lens.items()
                   if args.n_per_length > n}
        if too_big:
            raise SystemExit(
                f"--n-per-length {args.n_per_length} exceeds the pinned grid "
                f"at {too_big}. A larger n is not a prefix of anything "
                f"already measured, so those rows would be unpaired.")
        selected_seq_lens = {s: args.n_per_length for s in selected_seq_lens}

    # Clocks: attempt, then stamp what HAPPENED, never what was asked for.
    # Every row in this project so far carries clocks_locked=False because
    # nothing has ever passed the flag -- capture() takes it as a parameter
    # defaulting to False and does not observe it. So a run whose clocks ARE
    # pinned would be recorded as unpinned, and the fact would be lost.
    clocks_locked = False
    if args.lock_clocks and not args.dry_run:
        clocks_locked = provenance.lock_clocks()
        print(f"clocks        : lock {'SUCCEEDED' if clocks_locked else 'FAILED'} "
              f"-- stamped on every row as clocks_locked={clocks_locked}")

    def provenance_fn():
        return provenance.capture(clocks_locked=clocks_locked)

    # One name, resolved once. Every later use reads model_id, never
    # grid.model_primary, so an override cannot apply to the tokenizer and
    # miss the model (or the reverse) -- that split is how a run ends up
    # tokenizing with one vocabulary and generating with another.
    model_id = args.model or grid.model_primary
    if args.model and not args.dry_run:
        _guard_model_fits(model_id, args.device)

    print(f"grid          : {args.grid}")
    print(f"model primary : {model_id}"
          + ("   [--model OVERRIDE; grid pins "
             f"{grid.model_primary}]" if args.model else ""))
    print(f"model alt     : {grid.model_alternate}")
    print(f"tasks         : {', '.join(selected_tasks)}"
          + ("" if len(selected_tasks) == len(grid.tasks)
             else f"   [SUBSET of {len(grid.tasks)}]"))
    print("seq_lens (n)  : " + ", ".join(
        f"{s}{'*' if grid.is_directional(s) else ''}={n}"
        for s, n in sorted(selected_seq_lens.items()))
        + ("" if len(selected_seq_lens) == len(grid.seq_lens)
           else f"   [SEGMENT: {len(grid.seq_lens) - len(selected_seq_lens)} "
                f"of {len(grid.seq_lens)} bands held back]"))
    print("                (* = directional/underpowered point, see stage3_grid.yaml)")

    # Contexts are sized against a real tokenizer so a grid seq_len is an
    # exact token count (see attnbench/accuracy/sizing.py). A --dry-run only
    # exercises planning/cell-counting and must not require downloading a
    # tokenizer, so it uses the explicitly-named approximate counter -- and
    # says so, because a silent estimate is the failure this replaced.
    if args.dry_run:
        print("sizing        : APPROXIMATE (--dry-run; no tokenizer loaded) "
              "-- context lengths are structural only, not real token counts")
        count_tokens = approximate_token_count
    else:
        from transformers import AutoTokenizer
        tokenizer = AutoTokenizer.from_pretrained(model_id)

        def count_tokens(text: str) -> int:
            return len(tokenizer(text).input_ids)

        print(f"sizing        : exact, via {model_id} tokenizer")

    examples_by_task_length = build_examples_by_task_length(
        grid, seed=args.seed, count_tokens=count_tokens,
        tasks=selected_tasks, seq_lens=selected_seq_lens)
    examples_by_id = {
        (task, ex.example_id): ex
        for (task, _seq_len), exs in examples_by_task_length.items()
        for ex in exs
    }

    configs_by_backend = build_configs_by_backend(
        grid, include_sage=args.include_sage,
        seq_lens=tuple(selected_seq_lens),
        include_gla=not args.no_gla)
    if args.only_backends is not None:
        want = [b.strip() for b in args.only_backends.split(",") if b.strip()]
        unknown = [b for b in want if b not in configs_by_backend]
        if not want or unknown:
            raise SystemExit(
                f"--only-backends names {unknown or '(nothing)'}; this run's "
                f"backends are {list(configs_by_backend)}. The filter narrows "
                f"the grid; it cannot add to it.")
        configs_by_backend = {b: c for b, c in configs_by_backend.items()
                              if b in want}
    print(f"backends      : {', '.join(configs_by_backend)}")
    print("caps (tokens) : " + ", ".join(
        f"{t}={stopping.token_cap(t)}" for t in selected_tasks))

    cells = build_cells(configs_by_backend=configs_by_backend,
                        examples_by_task_length=examples_by_task_length)

    if args.dry_run:
        generate_fn = _dry_run_only
        teardown = None
    else:
        generate_fn = build_generate_fn(
            grid, model_id=model_id, tokenizer=tokenizer,
            device=args.device, dtype=args.dtype,
            score_cache_dir=grid.score_cache_dir,
            gla_gate_source=args.gla_gate_source,
            score_source=args.score_source)
        teardown = generate_fn.unwrap

    try:
        report = run_accuracy(cells, out_dir=Path(args.out),
                              examples_by_id=examples_by_id,
                              generate_fn=generate_fn, dry_run=args.dry_run,
                              provenance_fn=provenance_fn,
                              allow_mixed_commits=args.allow_mixed_commits,
                              allow_dirty=args.allow_dirty,
                              score_source=args.score_source)
    finally:
        if teardown is not None:
            teardown()

    print(f"\ntotal cells   : {report.total}")
    print(f"would run     : {report.run}")
    print(f"skip (done)   : {report.skip_done}")
    if args.dry_run:
        print("\n[dry run -- nothing executed, nothing written]")
    else:
        print(f"\nwritten to {args.out}/accuracy.parquet")


if __name__ == "__main__":
    main()
